### ISSUE TITLE
💡 Stamp: add support for base64 encoding binary files

### ISSUE THREAD

**Issue by breck7** [breck7/scrollsdk#118]
It looks like we haven't added support for binary files yet:

<img width="409" alt="Screen Shot 2021-02-23 at 5 02 44 AM" src="https://user-images.githubusercontent.com/74692/108862491-5ebd3580-7594-11eb-8b9a-5871053ea01b.png">

What's the best approach for deciding whether to encode as text or binary?

**Comment by SRS-WRKS** [comment]
@breck7 : Are binary files added inline or attached to or pointed to by the jtree input file ?

**Comment by breck7** [comment]
We can easily add if there ever is urgent demand, but not sure there ever will be. At that point proably best to use zip.
