### ISSUE TITLE
Missing HTML elements in Stump

### ISSUE THREAD

**Issue by getflourish** [breck7/scrollsdk#127]
When playing with Stump, I’ve noticed that the `<cite>` tag was missing. I then figured that the list might be hand-compiled.

For a full reference on available HTML tags, this might be a source:
https://github.com/mdn/browser-compat-data/tree/master/html/elements

I wish the repo had a simple index.json file containing just the names …

**Comment by getflourish** [comment]
Yeah that could be an approach! 

I guess it depends if all elements should be included or only "non deprecated" ones?

E.g. https://github.com/mdn/browser-compat-data/blob/main/html/elements/spacer.json

**Comment by breck7** [comment]
Only elements that are not deprecated should be included.

Except for blink. (https://github.com/mdn/browser-compat-data/blob/main/html/elements/blink.json). Blink must be included 😉

**Comment by breck7** [comment]
Would be neat but low pri
