### ISSUE TITLE
🚀 Create walkthrough of JTree codebase

### ISSUE THREAD

**Issue by breck7** [breck7/scrollsdk#129]
Per LU's suggestion, I should make a walkthrough of the JTree codebase.

Would also be a good opportunity to explain the constants/things changing
in the big UX upgrade.

**Comment by adz5a** [comment]
Hello,

Thank you for your work, it is amazing. I would like to make an implementation of this in Clojure/ClojureScript. Would you be able to guide me in this endeavour ? I'm available for a quick chat or anything anytime.

Have a great day ;)

**Comment by SRS-WRKS** [comment]
Hi @breck7 ,
I could try this

**Comment by SRS-WRKS** [comment]
@breck7 , how to proceed on this ( Do you have any resources for people who wish to begin this task) ?
Is this just source code documentation or does is it aimed for implementations in other languages ?
