### ISSUE TITLE
Parsers: add dependent types (or constraints)

### ISSUE THREAD

**Issue by breck7** [breck7/scrollsdk#148]
Problem: be able to add better validation logic to both maintain clean data and also improve autocomplete.

Example situation: someone adds a line `type visualLanguage` to a tree, then perhaps certain lines would now be invalidated while others would be required/recommended.

Could be done with a 3rd category of thing (cell types, nodetypes, contraint types), or perhaps could start with a smaller surface area and grow to that.

**Comment by SRS-WRKS** [comment]
Yes being explicit about which keys in a database are optional and which are not would be really nice. 
Right now if i am not mistaken databases keys can have syntax check for values but nothing more.

**Comment by breck7** [comment]
Would be neat but low pri
