### ISSUE TITLE
🚀 Parsers: Implement Language Server Protocol for Parsers

### ISSUE THREAD

**Issue by breck7** [breck7/scrollsdk#2]

**Comment by boticello** [comment]
This would be a great feature. I'm planning to create DSLs for use in VS Code (and other editors) and Tree Notation looks ideal. At the moment it looks like I'll need to use Xtext to recreate the grammar definition and generate the Language Server definitions. It would be perfect if Tree Notation could do it all. I'm sure it's not simple, though.

**Comment by breck7** [comment]
I agree @boticello! This would be so useful. Maybe next time I get a sprint.

**Comment by breck7** [comment]
closing in favor of this root issue: https://github.com/breck7/scroll/issues/114
